Repository Sayshal/hero-mancer, pull requests merged in 2025-04, with the labels that each got.

#128 Add `documentsReady` Hook!
  scripts/utils/documentService.js
Labels: enhancement

#130 1.0.3
  scripts/api.js
  scripts/hero-mancer.js
  scripts/utils/documentService.js
  scripts/utils/equipment/equipmentParser.js
  scripts/utils/index.js
Labels: enhancement

#132 Journal based descriptions
  .gitignore
  lang/en.json
  scripts/app/HeroMancer.js
  scripts/hero-mancer.js
  scripts/utils/DOMManager.js
  scripts/utils/descriptionBuilder.js
  scripts/utils/documentService.js
  scripts/utils/equipment/equipmentParser.js
  scripts/utils/equipment/equipmentRenderer.js
  scripts/utils/equipment/index.js
  scripts/utils/equipment/renderers/focusItemRenderer.js
  scripts/utils/equipment/renderers/linkedItemRenderer.js
  scripts/utils/equipment/renderers/orItemRenderer.js
  scripts/utils/equipment/renderers/toolItemRenderer.js
  scripts/utils/index.js
  styles/_abilities.css
  styles/_animation.css
  styles/_application.css
  styles/_equipment.css
  styles/_finalize.css
  styles/_forms.css
  styles/_journal.css
  styles/_layout.css
  styles/_popups.css
  styles/_responsive.css
  styles/_transitions.css
  styles/_utilities.css
  styles/_variables.css
  styles/hero-mancer.css
  templates/tab-background.hbs
  templates/tab-class.hbs
  templates/tab-race.hbs
Labels: enhancement

#136 1.2.1
  lang/de.json
  lang/en.json
  scripts/utils/descriptionBuilder.js
  scripts/utils/documentService.js
  scripts/utils/equipment/equipmentParser.js
  scripts/utils/equipment/equipmentRenderer.js
  scripts/utils/equipment/renderers/andItemRenderer.js
  scripts/utils/equipment/renderers/baseItemRenderer.js
  scripts/utils/equipment/renderers/focusItemRenderer.js
  scripts/utils/equipment/renderers/linkedItemRenderer.js
  scripts/utils/equipment/renderers/orItemRenderer.js
  scripts/utils/equipment/renderers/toolItemRenderer.js
  scripts/utils/randomizer.js
  styles/_equipment.css
  styles/_forms.css
  styles/_journal.css
  styles/hero-mancer.css
  templates/app-footer.hbs
Labels: bug, enhancement, design

#138 Brazilian Portuguese Translation
  lang/pt-BR.json
  module.json
Labels: enhancement

#143 1.2.3
  lang/en.json
  lang/pt-BR.json
  scripts/app/HeroMancer.js
  scripts/app/MandatoryFields.js
  scripts/hero-mancer.js
  scripts/settings.js
  scripts/utils/DOMManager.js
  scripts/utils/actorCreationService.js
  scripts/utils/statRoller.js
  styles/_application.css
  templates/app-footer.hbs
  templates/tab-abilities.hbs
  templates/tab-start.hbs
Labels: bug, enhancement, design

#150 1.2.5
  lang/de.json
  lang/en.json
  lang/pt-BR.json
  scripts/app/CustomCompendiums.js
  scripts/app/Customization.js
  scripts/app/DiceRolling.js
  scripts/app/HeroMancer.js
  scripts/app/MandatoryFields.js
  scripts/app/Troubleshooter.js
  scripts/hero-mancer.js
  scripts/settings.js
  scripts/utils/DOMManager.js
  scripts/utils/characterArtPicker.js
  scripts/utils/descriptionBuilder.js
  scripts/utils/equipment/equipmentParser.js
  scripts/utils/equipment/equipmentRenderer.js
  scripts/utils/equipment/renderers/andItemRenderer.js
  scripts/utils/equipment/renderers/baseItemRenderer.js
  scripts/utils/equipment/renderers/focusItemRenderer.js
  scripts/utils/equipment/renderers/toolItemRenderer.js
  scripts/utils/formValidation.js
  scripts/utils/statRoller.js
  scripts/utils/tableManager.js
  styles/_abilities.css
  styles/_animation.css
  styles/_application.css
  styles/_equipment.css
  styles/_finalize.css
  styles/_forms.css
  styles/_journal.css
  styles/_layout.css
  styles/_popups.css
  styles/_responsive.css
  styles/_transitions.css
  styles/_utilities.css
  styles/_variables.css
  styles/hero-mancer.css
  templates/settings/customization.hbs
  templates/tab-abilities.hbs
  templates/tab-background.hbs
  templates/tab-class.hbs
  templates/tab-race.hbs
Labels: bug, enhancement, epic, design
